# Site settings
title:          BCS
description:    "long-suffering BTS fan"
url:            "https://binkymilk.github.io"

# Author
author:
  name:         Bianca Silmaro
  url:          https://www.twitter.com/binkymilk
  email:        biancasilmaro@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
